--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaRealAqua/CustomTags
build-by-default: true
branches:
- main
projects:
  CustomTags:
    path: "https://static.wikia.nocookie.net/minecraft_de_gamepedia/images/a/aa/Namensschild.png/revision/latest/scale-to-width-down/160?cb=20200413193354"
...
