---
# This plugin was made by DaRealAqua with Love^_^
#
# Levania Network Discord: https://discord.gg/Axa33MgXJ9
#
# CONTACT ME ON:
# Discord: DaRealAqua#9324
# Twitter: @Levania_Network
#
# How to create a tag:
# tags:
#   tagName:
#     name: "nameColored"
#     perm: "Permission"
#     cost: "amount$$"
#
# Tags: {line}, {money}, {tag}, {cost}, {player}, {permission}

# Display the tag of the player
chat-format: "{tag} {player}"

# Tags List
tags:
  levania:
    name: "§l§aLevania§r"
    perm: levania.tag
    cost: 1000
  darealaqua:
    name: "§l§bDaRealAqua§r"
    perm: darealaqua.tag
    cost: 5000
  aquadevs:
    name: "§l§bAqua§eDevs§r"
    perm: aquadevs.tag
    cost: 10000

# Main menu of the Tags Menu
# Category Selector Menu
menu-selector:
  title: "Tags Menu"
  content: "§7Your current money:§c ${money}{line}§7Your current tag:§c {tag}{line}§r§7Select a category"
  tags-button: "Available Tags{line}Click to Open"
  shop-button: "Buy Tags{line}Click to Open"
  exit-button: "§cExit the Menu"
# Equip the tag u want, if you have the permission
# Tags Menu
menu-tags:
  title: "Available Tags"
  content: "§7Your current tag: §c{tag}"
  locked-button: "{tag}{line}§r§cNot Available"
  unlocked-button: "{tag}{line}§r§aAvailable"
# Buy a tag
# Tags Shop Menu
menu-shop:
  title: "Tags Shop"
  content: "§7Your current money:§c ${money}"
  button: "{tag}{line}§r§c${cost}"
  # PureChat and PurePerm I currently use to set a player's permission but if you want you can use your own plugin.
  command: "setuperm {player} {permission}"
...
